[tasks."backend:dev"]
dir = "backend"
run = "./make.sh run_dev"

[tasks."backend:lint"]
dir = "backend"
run = "./make.sh lint"

[tasks."backend:test"]
dir = "backend"
run = "./make.sh test"

[tasks."deployment:setup"]
dir = "deployment"
run = "./make.sh setup"

[tasks."deployment:deploy"]
dir = "deployment"
run = "./make.sh deploy --environment production"

[tasks."deployment:infrastructure"]
dir = "deployment"
run = "./make.sh infrastructure --environment production"

[tasks."deployment:kubeconfig"]
dir = "deployment"
run = "./make.sh kubeconfig --environment production"

[tasks."deployment:backup"]
dir = "deployment"
run = "./make.sh backup --environment production"

[tasks."deployment:restore"]
dir = "deployment"
run = "./make.sh restore --environment production"

[tasks."deployment:update-vms"]
dir = "deployment"
run = "./make.sh update_vms --environment production"

[tasks."deployment:k3s-upgrade"]
dir = "deployment"
run = "./make.sh k3s_upgrade --environment production"
[tools]
node = "24"

[tasks."e2e:test"]
dir = "e2e_tests"
run = "./make.sh test_e2e"

[tasks.dev]
depends = ["auth:up"]
run = "mise run backend:dev ::: frontend:dev"

[tasks."frontend:dev"]
dir = "frontend"
run = "./make.sh run_dev"

[tasks."frontend:lint"]
dir = "frontend"
run = "./make.sh lint"

[tasks."frontend:test"]
dir = "frontend"
run = "./make.sh test"

[tasks."auth:up"]
dir = "oauth2-proxy"
run = "./make.sh auth_up"

[tasks."auth:down"]
dir = "oauth2-proxy"
run = "./make.sh auth_down"
