---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: "{{ k8s_namespace | default('default') }}"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
