name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - deployment/**
      - backend/deployment/**
      - frontend/deployment/**
      - oauth2-proxy/deployment/**
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment which should be deployed'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    uses: §§deploy_your_startup.github_username§§/§§deploy_your_startup.deploy_repo_name§§/.github/workflows/deploy.yml@main
    with:
      environment: ${{ github.event.inputs.environment || inputs.environment }}
    secrets:
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
